### ISSUE TITLE
first smart contract

### ISSUE THREAD

**Issue by 689itzjack** [689itzjack/Intelligent-Signature-System#13]
here we will create our first prototype of smart contract for our project

**Comment by ofircohen205** [comment]
I went through [createVote.sol](https://github.com/689itzjack/Intelligent-Signature-System/blob/Contract0.0.1/contracts/createVote.sol) and I think I own you some prior knowledge on smart contract programming.

The smart contract can be thought of as a factory of instances. every time we deploy a smart contract to the blockchain, what happens is that we are creating an instance of the type of smart contract, with a unique identifier (in Ethereum, it's the Ethereum address)

So, in our project, we will have a smart contract of "CourseExamVotes", where an instance of the smart contract will be for example votes to change the date of "Operating Systems".


Now, after we are aligned with this thought, we can start with the smart contract prototype.

**Global variables:**
owner address (the one who deployed the contract)
course id
semester
moed exam
mapping between dates to the number of votes
... think what else you'll need.

**Constructor:**
the constructor will get the possible dates given by the exams administrator, and another variable to identify the exam (course id, semester, moed)
something to think about - we would like the voting before the deadline given by the exam administrator. how we can be sure that the students voted before it? hint: use timestamps

**Functions**
The most important function we need is the voting function. the function needs to get the wanted date and an id for the student that voted. we need to make sure that the student didn't work twice, and that the date is valid, i.e. it is in our allowed dates. (for the latter requirement, we will verify it both in the frontend and in the smart contract)

Another important function is when the voting is finished, how do we know the new date for the exam?
recall that we are saying that the new date is the one with the maximum number of votes.

Think of other functions that we will need.


One more thing, we need to think about how our variables and functions (at least some of them) are secured and being called by only those authorized.

**Comment by 689itzjack** [comment]
I have finished the  smart contract nominated to be the smart contract usable for the students users
