### ISSUE TITLE
OVERWRITING

### ISSUE THREAD

**Issue by 689itzjack** [689itzjack/Intelligent-Signature-System#21]
HII OFIR.
I want to pass all the files already created in my hard hat project to the new project of React, but I dont want to overwrite the files with the same name (for example the file package.json or the carpet node-modules) because maybe it will bring  problems now or in the future, I want just add the data of the files in one file with the same name. 
Thanks.

**Comment by ofircohen205** [comment]
what you can do is inside the main folder have 2 sub folders named "contracts" and "frontend"
In the contracts sub folder you'll have the relevant files for the smart contract and solidity files,
and in the frontend sub folder you'll have the relevant files for the frontend.

For example:
- intelligent_signature_system:
    - contracts: inside of it smart contract project
    - frontend: inside of it react project
