### ISSUE TITLE
Problem Description

### ISSUE THREAD

**Issue by 689itzjack** [689itzjack/Intelligent-Signature-System#7]
This is the part of the problem description in the project.
Hi Ophir I dont kwow exactly what to do here.

**Comment by 689itzjack** [comment]
Hi Ophir I would to know what exactly have to to in this section.
Thanks.

**Comment by ofircohen205** [comment]
Think about our issue:
In order to change the dates of exams in the academy, the students need to gather signatures from all students manually.
This process is time consuming on getting all signatures, where if we had a service that helps us.

Some may ask why use blockchain mechanism - we can say that a malicious person can hack into the servers where we store the results, where in blockchain if the person wants to hack our results he need to overcome the longest chain.

**Comment by 689itzjack** [comment]
**דרישות ואפיון  הבעיה 
1. תת פרק זה מכיל אפיון של הדרישות מנקודת מבט המשתמש. למשל עבור פרויקט המציג מסכים ותפריטים  למשתמש – תת פרק זה יתאר את  המסכים העיקריים. 
הנספח יכיל את רשימות הדרישות מהפרויקט.

2. הבעיה מבחינת הנדסת תוכנה
תת סעיף זה מתאר את האתגרים הצפויים והייחוד של הפרויקט מבחינת הנדסת תוכנה**

שלום אופיר. הטקסט הקודם זה מהמסמך של הדו"ח הצעה של הפרויקט הגמר בחלק של "תיאור הבעיה". השאלות שלי הן:
1. מה הכוונה שלו בלכתוב דרישות או איפיון של הדרישות מנקודת מבט המשתמש? ומה הכוונה של "הנספח יכיל את רשימות הדרישות מהפרויקט."
2. מה הכוונה של "הבעיה מבחינת הנדסת תוכנה "?

לא מצליח להבין איך לעשות ולענות על השאלות האלו
תודה רבה 
יצחק

**Comment by ofircohen205** [comment]
**1. דרישות ואפיון הבעיה -** הקטע כולל פירוט את הבעיה באופן ״כללי״, כלומר אתה מתאר את הבעיה שלנו.
לצורך העניין אצלנו בפרויקט הבעיה היא שאם סטודנטים בחוג מסוים רוצים להעביר תאריך של בחינה אז הם צריכים לאסוף חתימות של כל הסטודנטים, שזה תהליך איטי שאפשר לעשות לו אוטומציה.
זה בגדול הבסיס, אתה יכול גם לפרט את הצורך של המשתמש (במקרה שלנו, הסטודנטים) לבקש לשנות תאריכי בחינות מטעמי נוחות / התנגשות  בין בחינות וכד׳.


**2. הבעיה מבחינת הנדסת תוכנה -** הקטע כולל הסבר על אתגרים שיכולים להיות בפרויקט מהצד של הנדסת התוכנה (או במילים אחרת, כשאתה תגיע למימוש איפה יכול להיות בעיות מורכבות).
למשל אצלנו בפרויקט, אנחנו רוצים שסטודנט x מחוג y לא יוכל להצביע לשינוי בחינה בחוג z.
לכן מדובר פה באיזשהו אתגר לדעת להציג לאותו סטודנט את רשימת הקורסים שרלוונטיים אליו בלבד.
בנוסף, עוד אתגר שיכול להופיע הוא כאשר רכז הבחינות של המכללה ירצה לראות תוצאות הצבעה של הזזת מבחן מסוים, כיצד נוכל לשלוף את המידע מה-blockchain שרלוונטי רק עבור אותו מבחן?

**Comment by 689itzjack** [comment]
יופי הבנתי תודה רבה אופיר
